const questionsByCountry = {
  Canada: [
    {
      step: 2,
      question: "What is your age range?",
      type: "dropdown",
      options: ["18–24", "25–32", "33–39", "40–49", "50–59", "60+"],
    },
    {
      step: 3,
      question: "What is your highest level of education?",
      type: "dropdown",
      options: [
        "Doctorate (PhD)",
        "Master’s Degree",
        "Bachelor’s Degree",
        "Diploma / Trade Certificate",
        "12th Pass / Senior Secondary",
        "Below 12th",
      ],
    },
    {
      step: 4,
      title: "Work Profile & Experience",
      questions: [
        {
          q: "How many years of work experience do you have?",
          type: "dropdown",
          options: [
            "Less than 1 year",
            "1–2 years",
            "3–4 years",
            "5–7 years",
            "8+ years",
          ],
        },
        {
          q: "What is your field of work?",
          type: "dropdown+text", // dropdown + text input for "Other"
          options: [
            "STEM (IT/Engineering/Science)",
            "Healthcare/Medicine",
            "Business/Management/Finance",
            "Law",
            "Arts/Design/Media",
            "Humanities/Social Sciences",
            "Other",
          ],
        },
      ],
    },
    {
      step: 5,
      title: "Language Proficiency",
      questions: [
        {
          q: "What is your English language proficiency level?",
          type: "dropdown",
          options: [
            "Very High Proficiency",
            "High Proficiency",
            "Moderate Proficiency",
            "Basic Proficiency",
            "No Proficiency",
          ],
        },
        {
          q: "What is your French language proficiency level?",
          type: "dropdown",
          options: [
            "Very High Proficiency",
            "High Proficiency",
            "Moderate Proficiency",
            "Basic Proficiency",
            "No Proficiency",
          ],
        },
      ],
    },
    {
      step: 6,
      question: "Are you married?",
      type: "yes-no",
    },
    {
      step: 7,
      title: "Assessing Your Adaptability Factors",
      questions: [
        { q: "Have you previously studied in Canada?", type: "yes-no" },
        {
          q: "Do you have close adult relatives (family) living in Canada?",
          type: "yes-no",
        },
        {
          q: "Does your spouse have recognized English/French language credentials (IELTS/CELPIP/TEF)?",
          type: "yes-no",
        },
        { q: "Do you have previous Canadian work experience?", type: "yes-no" },
      ],
    },
    {
      step: 8,
      question: "What is your Net worth?",
      type: "text",
    },
    {
      step: 9,
      question: "Choose the visa category you want to apply.",
      type: "dropdown",
      options: [
        "PR Visa",
        "Study Visa",
        "Work Permit",
        "Spouse/Family Visas",
        "Business & Investor Visas",
        "Job Visa",
        "Visit/ Tourist Visa",
      ],
    },
    // { step: 10, info: "Almost There! Please fill in the form to continue." },
    // { step: 11, info: "Congratulations! You’re likely to qualify. 🎉" },
  ],

  Australia: [
    {
      step: 2,
      question: "What is your age range?",
      type: "dropdown",
      options: ["18–24", "25–32", "33–39", "40–49", "50–59", "60+"],
    },
    {
      step: 3,
      question: "What is your highest level of education?",
      type: "dropdown",
      options: [
        "Doctorate (PhD)",
        "Master’s Degree",
        "Bachelor’s Degree",
        "Diploma / Trade Certificate",
        "12th Pass / Senior Secondary",
        "Below 12th",
      ],
    },
    {
      step: 4,
      title: "Work Profile & Experience",
      questions: [
        {
          q: "How many years of skilled work experience do you have?",
          type: "dropdown",
          options: [
            "Less than 1 year",
            "1–2 years",
            "3–4 years",
            "5–7 years",
            "8+ years",
          ],
        },
        {
          q: "What is your field of work?",
          type: "dropdown+text",
          options: [
            "STEM (IT/Engineering/Science)",
            "Healthcare/Medicine",
            "Business/Management/Finance",
            "Law",
            "Arts/Design/Media",
            "Humanities/Social Sciences",
            "Other",
          ],
        },
      ],
    },
    {
      step: 5,
      question: "What is your English language proficiency level?",
      type: "dropdown",
      options: [
        "Very High Proficiency",
        "High Proficiency",
        "Moderate Proficiency",
        "Basic Proficiency",
        "No Proficiency",
      ],
    },
    {
      step: 6,
      question: "Do you have any of the following?",
      type: "dropdown",
      options: [
        "State/Territory Nomination",
        "Job Offer from an Australian Employer",
        "Family Sponsorship in Regional Area",
        "No job offer/sponsorship yet",
      ],
    },
    {
      step: 7,
      question: "Are you married?",
      type: "yes-no",
    },
    {
      step: 8,
      title: "Additional Factors",
      questions: [
        {
          q: "Have you completed at least 2 years of study in Australia?",
          type: "yes-no",
        },
        {
          q: "Have you worked in Australia for at least 1 year?",
          type: "yes-no",
        },
        {
          q: "Does your partner have skilled occupation and/or English proficiency that can add points?",
          type: "dropdown",
          options: ["Yes", "No", "Not Applicable (Single)"],
        },
        {
          q: "Do you hold NAATI (Community Language) Certification?",
          type: "yes-no",
        },
      ],
    },
    { step: 9, question: "What is your Net worth?", type: "text" },
    {
      step: 10,
      question: "Choose the visa category you want to apply.",
      type: "dropdown",
      options: [
        "PR Visa",
        "Study Visa",
        "Work Permit",
        "Spouse/Family Visas",
        "Business & Investor Visas",
        "Employer Nomination Visa",
        "Visit/ Tourist Visa",
      ],
    },
    // { step: 11, info: "Almost There! Please fill in the form to continue." },
    // { step: 12, info: "Congratulations! You’re likely to qualify. 🎉" },
  ],

  UK: [
    {
      id: 2,
      type: "dropdown",
      title: "What is your age range?",
      options: ["18–24", "25–32", "33–39", "40–49", "50–59", "60+"],
    },
    {
      id: 3,
      type: "dropdown",
      title: "What is your highest level of education?",
      options: [
        "Doctorate (PhD)",
        "Master’s Degree",
        "Bachelor’s Degree",
        "Diploma / Trade Certificate",
        "12th Pass / Senior Secondary",
        "Below 12th",
      ],
    },
    {
      id: 4,
      type: "dropdown",
      title: "How many years of skilled work experience do you have?",
      options: [
        "Less than 1 year",
        "1–2 years",
        "3–4 years",
        "5–7 years",
        "8+ years",
      ],
    },
    {
      id: 4.1,
      type: "dropdown",
      title: "What is your field of work?",
      options: [
        "STEM (IT/Engineering/Science)",
        "Healthcare/Medicine",
        "Business/Management/Finance",
        "Law",
        "Arts/Design/Media",
        "Humanities/Social Sciences",
        "Other",
      ],
    },
    {
      id: 5,
      type: "dropdown",
      title: "What is your English language proficiency level?",
      options: [
        "Very High Proficiency",
        "High Proficiency",
        "Moderate Proficiency",
        "Basic Proficiency",
        "No Proficiency",
      ],
    },
    {
      id: 6,
      type: "yes-no",
      title:
        "Do you hold a job offer from UK and an approved sponsor, and is it at an appropriate skill level?",
      options: ["Yes", "No"],
    },
    {
      id: 7,
      type: "yes-no",
      title: "Are you married?",
      options: ["Yes", "No"],
    },
    { id: 8, type: "text", title: "What is your Net worth?" },
    {
      id: 9,
      type: "dropdown",
      title: "Choose the visa category you want to apply.",
      options: [
        "PR Visa",
        "Study Visa",
        "Work Permit",
        "Spouse/Family Visas",
        "Business & Investor Visas",
        "Job Visa",
        "Visit/ Tourist Visa",
      ],
    },
  ],

  USA: [
    {
      id: 2,
      type: "dropdown",
      title: "What is your age range?",
      options: ["18–24", "25–32", "33–39", "40–49", "50–59", "60+"],
    },
    {
      id: 3,
      type: "dropdown",
      title: "What is your highest level of education?",
      options: [
        "Doctorate (PhD)",
        "Master’s Degree",
        "Bachelor’s Degree",
        "Diploma / Trade Certificate",
        "12th Pass / Senior Secondary",
        "Below 12th",
      ],
    },
    {
      id: 4,
      type: "dropdown",
      title: "How many years of work experience do you have?",
      options: [
        "Less than 1 year",
        "1–2 years",
        "3–4 years",
        "5–7 years",
        "8+ years",
      ],
    },
    {
      id: 4.1,
      type: "dropdown",
      title: "What is your current employment type?",
      options: [
        "Full-time, salaried employee",
        "Part-time employee",
        "Self-employed / Entrepreneur / Freelancer",
        "Business owner with employees",
        "Student (not working)",
        "Unemployed / Gap period",
      ],
    },
    {
      id: 4.2,
      type: "dropdown",
      title: "What is your field of work?",
      options: [
        "STEM (IT/Engineering/Science)",
        "Healthcare/Medicine",
        "Business/Management/Finance",
        "Law",
        "Arts/Design/Media",
        "Humanities/Social Sciences",
        "Other",
      ],
    },
    {
      id: 5,
      type: "dropdown",
      title: "What is your English language proficiency level?",
      options: [
        "Very High Proficiency",
        "High Proficiency",
        "Moderate Proficiency",
        "Basic Proficiency",
        "No Proficiency",
      ],
    },
    {
      id: 6,
      type: "yes-no",
      title: "Are you married?",
      options: ["Yes", "No"],
    },
    { id: 7, type: "text", title: "What is your Net worth?" },
    {
      id: 8,
      type: "dropdown",
      title: "Choose the visa category you want to apply.",
      options: [
        "Visit – Tourism/Family (B-2)",
        "Business Visit – Meetings/Conference (B-1)",
        "Study (F-1 / M-1)",
        "Work – US employer sponsorship (H-1B)",
        "Intra-company transfer (L-1A/L-1B)",
        "Extraordinary ability/Arts/Sports/Research (O-1)",
        "Exchange program/Training (J-1)",
        "Employment-based Green Card (EB-1/EB-2/EB-3)",
        "Invest for Green Card (EB-5)",
        "Family/Spouse/Fiancé(e) sponsorship (IR/CR/K-1)",
        "Startup founder/entrepreneur (O-1A or IEP)",
      ],
    },
  ],

  NewZealand: [
    {
      id: 2,
      type: "dropdown",
      title: "What is your age range?",
      options: ["18–24", "25–32", "33–39", "40–49", "50–59", "60+"],
    },
    {
      id: 3,
      type: "dropdown",
      title: "What is your highest level of education?",
      options: [
        "Doctorate (PhD)",
        "Master’s Degree",
        "Bachelor’s Degree",
        "Diploma / Trade Certificate",
        "12th Pass / Senior Secondary",
        "Below 12th",
      ],
    },
    {
      id: 4,
      type: "dropdown",
      title: "How many years of skilled work experience do you have?",
      options: [
        "Less than 1 year",
        "1–2 years",
        "3–4 years",
        "5–7 years",
        "8+ years",
      ],
    },
    {
      id: 4.1,
      type: "dropdown",
      title: "What is your field of work?",
      options: [
        "STEM (IT/Engineering/Science)",
        "Healthcare/Medicine",
        "Business/Management/Finance",
        "Law",
        "Arts/Design/Media",
        "Humanities/Social Sciences",
        "Other",
      ],
    },
    {
      id: 5,
      type: "dropdown",
      title: "What is your English language proficiency level?",
      options: [
        "Very High Proficiency",
        "High Proficiency",
        "Moderate Proficiency",
        "Basic Proficiency",
        "No Proficiency",
      ],
    },
    {
      id: 6,
      type: "dropdown",
      title:
        "Do you have an acceptable skilled job or job offer in New Zealand?",
      options: [
        "Currently working in New Zealand in a skilled role",
        "Have a formal job offer in New Zealand",
        "No job or job offer yet",
      ],
    },
    {
      id: 7,
      type: "yes-no",
      title: "Are you married?",
      options: ["Yes", "No"],
    },
    {
      id: 8,
      type: "multi-yes-no",
      title: "Additional factors",
      subQuestions: [
        "Completed 2 years of study in New Zealand?",
        "Worked in New Zealand for 1 year?",
      ],
    },
    { id: 9, type: "text", title: "What is your Net worth?" },
    {
      id: 10,
      type: "dropdown",
      title: "Choose the visa category you want to apply.",
      options: [
        "PR Visa",
        "Study Visa",
        "Work Permit",
        "Spouse/Family Visas",
        "Business & Investor Visas",
        "Job Visa",
        "Visit/ Tourist Visa",
      ],
    },
  ],

  Europe: [
    {
      id: 2,
      type: "dropdown",
      title: "What is your age range?",
      options: ["18–24", "25–32", "33–39", "40–49", "50–59", "60+"],
    },
    {
      id: 3,
      type: "dropdown",
      title: "What is your highest level of education?",
      options: [
        "Doctorate (PhD)",
        "Master’s Degree",
        "Bachelor’s Degree",
        "Diploma / Trade Certificate",
        "12th Pass / Senior Secondary",
        "Below 12th",
      ],
    },
    {
      id: 4,
      type: "dropdown",
      title: "How many years of work experience do you have?",
      options: [
        "Less than 1 year",
        "1–2 years",
        "3–4 years",
        "5–7 years",
        "8+ years",
      ],
    },
    {
      id: 4.1,
      type: "dropdown",
      title: "What is your current employment type?",
      options: [
        "Full-time, salaried employee",
        "Part-time employee",
        "Self-employed / Entrepreneur / Freelancer",
        "Business owner with employees",
        "Student (not working)",
        "Unemployed / Gap period",
      ],
    },
    {
      id: 4.2,
      type: "dropdown",
      title: "What is your field of work?",
      options: [
        "STEM (IT/Engineering/Science)",
        "Healthcare/Medicine",
        "Business/Management/Finance",
        "Law",
        "Arts/Design/Media",
        "Humanities/Social Sciences",
        "Other",
      ],
    },
    {
      id: 5,
      type: "yes-no",
      title: "Are you married?",
      options: ["Yes", "No"],
    },
    { id: 6, type: "text", title: "What is your Net worth?" },
    {
      id: 7,
      type: "dropdown",
      title: "Choose the visa category you want to apply.",
      options: [
        "PR Visa/EU Blue Card",
        "Study Visa",
        "Work Permit",
        "Spouse/Family Visas",
        "Business & Investor Visas",
        "Job Seeker Visa",
        "Visit/ Tourist Visa",
      ],
    },
    { id: 8, type: "text", title: "Which European country do you prefer?" },
  ],
};

export default questionsByCountry;
