import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from "next-intl";
import {  routing } from "@/i18n/routing";
import { Poppins, Montserrat, Roboto,Mulish } from "next/font/google";
import "../globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600"], // regular to semi-bold
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "700"], // bold for headings
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500"], // normal text
});


const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});




export const metadata = {
  title: "Gloedge",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params  }) {
    const { locale } = await params;
  let messages;
  try {
     messages = await getMessages({ locale });

 
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${poppins.variable} ${montserrat.variable} ${roboto.variable} ${mulish.variable}  antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
